title: "ITP 382 Lab Guide"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: false
footer_content: "This site is intended for individual educational use only. Redistribution of this content is prohibited without prior approval from the ITP 380 instructors, and may be deemed an academic integrity violation."
